spring:
  application:
    name: spring-ai-rag
#Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
       options:
         model: text-embedding-3-small
sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - classpath:/movies500Trimmed.csv